/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Fri May 22 12:17:51 2020. */

#include "credentials.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ccParameters_fields[7] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, POINTER , FIRST, ccParameters, ccId, ccId, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, POINTER , OTHER, ccParameters, ccVersion, ccId, 0),
    PB_FIELD(  3, INT64   , OPTIONAL, POINTER , OTHER, ccParameters, ccSequence, ccVersion, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, POINTER , OTHER, ccParameters, channelId, ccSequence, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, POINTER , OTHER, ccParameters, mspId, channelId, 0),
    PB_FIELD(  6, BYTES   , OPTIONAL, POINTER , OTHER, ccParameters, tlccMREnclave, mspId, 0),
    PB_LAST_FIELD
};

const pb_field_t ccPublicKeys_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, POINTER , FIRST, ccPublicKeys, enclaveVerifyingKey, enclaveVerifyingKey, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, POINTER , OTHER, ccPublicKeys, enclaveEncryptionKey, enclaveVerifyingKey, 0),
    PB_LAST_FIELD
};

const pb_field_t ccPrivateKeys_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, POINTER , FIRST, ccPrivateKeys, enclaveSigningKey, enclaveSigningKey, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, POINTER , OTHER, ccPrivateKeys, enclaveDecryptionKey, enclaveSigningKey, 0),
    PB_LAST_FIELD
};

const pb_field_t credentials_fields[5] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, POINTER , FIRST, credentials, verb, verb, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, POINTER , OTHER, credentials, enclaveAttestation, verb, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, POINTER , OTHER, credentials, attestedData, enclaveAttestation, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, POINTER , OTHER, credentials, verificationReport, attestedData, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
