/*
 * Copyright 2020 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "test.h"
#include <string>
#include "base64.h"
#include "error.h"
#include "logging.h"

#include "verify-evidence.h"

bool test()
{
    std::string b64evidence(
        "eyJpYXNTaWduYXR1cmUiOiJGMXArdUQ2bFFmUW1OdE9qbkZZbWhGd1c1K0YxWjJ0STlFc3d3amhmM0pNSCtGYlozdU"
        "lXTlk4alk4N0I3Nk9GSlpEeWtIc2Juck1ybVQrZWlBRTlyeU5hS3JBa1JYNWpyNVhHNU8rZGF3U3N5ZWdKZzY3dHND"
        "RVpDdWFxRUFmbGJIbEg1NURDSWo1VEJqYVByU0l0ZVdRN2g2QmxaeXE3YlkzUFFybjJlT0lVRGxPQVRacDRTdDIxYz"
        "BKVThvZ2E2OUNjcmdCQ25BOXFvajVBMC9XNWt4ZUNYNklSWUtVMFpXaFkzUTRKWVFSOHdxc1VYcUwwSDF6cW93eTVW"
        "M0N3dFFtV1V5U0w3cmg0L1oxSUtxRzc1bmFHN29RZzNRWG5wbk0vVkx6M29rbU9yNkE5dFY3TlFxYlF0dUo2NUhaY1"
        "hyQ0NSVzdVSE5DekpQVVB3bTRkK2c9PSIsImlhc0NlcnRpZmljYXRlcyI6Ii0tLS0tQkVHSU4lMjBDRVJUSUZJQ0FU"
        "RS0tLS0tJTBBTUlJRW9UQ0NBd21nQXdJQkFnSUpBTkVIZGwweW83Q1dNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1INHhDek"
        "FKQmdOViUwQUJBWVRBbFZUTVFzd0NRWURWUVFJREFKRFFURVVNQklHQTFVRUJ3d0xVMkZ1ZEdFZ1EyeGhjbUV4R2pB"
        "WUJnTlYlMEFCQW9NRVVsdWRHVnNJRU52Y25CdmNtRjBhVzl1TVRBd0xnWURWUVFERENkSmJuUmxiQ0JUUjFnZ1FYUj"
        "BaWE4wJTBBWVhScGIyNGdVbVZ3YjNKMElGTnBaMjVwYm1jZ1EwRXdIaGNOTVRZeE1USXlNRGt6TmpVNFdoY05Nall4"
        "TVRJdyUwQU1Ea3pOalU0V2pCN01Rc3dDUVlEVlFRR0V3SlZVekVMTUFrR0ExVUVDQXdDUTBFeEZEQVNCZ05WQkFjTU"
        "MxTmglMEFiblJoSUVOc1lYSmhNUm93R0FZRFZRUUtEQkZKYm5SbGJDQkRiM0p3YjNKaGRHbHZiakV0TUNzR0ExVUVB"
        "d3drJTBBU1c1MFpXd2dVMGRZSUVGMGRHVnpkR0YwYVc5dUlGSmxjRzl5ZENCVGFXZHVhVzVuTUlJQklqQU5CZ2txaG"
        "tpRyUwQTl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxWG90NE9adXBoUjhudWRGckFGaWFHeHhrZ21hL0VzL0JB"
        "JTJCdCUwQWJlQ1RVUjEwNkFMMUVOY1dBNEZYM0slMkJFOUJCTDAvN1g1cmo1bklnWC9SLzF1YmhrS1d3OWdmcVBHM0"
        "tlQXRJZCUwQWN2L3VUTzF5WHY1MHZxYVB2RTFDUkNodnpkUy9aRUJxUTVvVnZMVFBaM1ZFaWNRamx5dEtnTjljTG54"
        "Ynd0dXYlMEFMVUs3ZXlSUGZKVy9rc2RkT3pQOFZCQm5pb2xZblJDRDJqck1SWjhuQk0yWldZd25YbndZZU9BSFYlMk"
        "JXOXRPaEElMEFJbXdSd0tGLzk1eUFzVndkMjFyeUhNSkJjR0g3MHFMYWdaN1R0eXQlMkIlMkJxTy82JTJCS0FYSnVL"
        "d1pxalJsRXRTRXo4JTBBZ1pRZUZmVllnY3dTZm85Nm9TTUF6VnI3VjBMNkhTRExSbnBiNnh4bWJQZHFOb2w0dFFJRE"
        "FRQUJvNEdrTUlHaCUwQU1COEdBMVVkSXdRWU1CYUFGSGhEZTNhbWZyelFyMzVDTiUyQnMxZkR1SEFWRThNQTRHQTFV"
        "ZER3RUIvd1FFQXdJRyUwQXdEQU1CZ05WSFJNQkFmOEVBakFBTUdBR0ExVWRId1JaTUZjd1ZhQlRvRkdHVDJoMGRIQT"
        "ZMeTkwY25WemRHVmslMEFjMlZ5ZG1salpYTXVhVzUwWld3dVkyOXRMMk52Ym5SbGJuUXZRMUpNTDFOSFdDOUJkSFJs"
        "YzNSaGRHbHZibEpsJTBBY0c5eWRGTnBaMjVwYm1kRFFTNWpjbXd3RFFZSktvWklodmNOQVFFTEJRQURnZ0dCQUdjSX"
        "RodGNLOUlWUno0ciUwQVJxJTJCWktFJTJCN2s1MC9PeFVzbVc4YWF2T3pLYjBpQ3gwN1lROXJ6aTVuVTczdE1FMnlH"
        "Ukx6aFNWaUZzL0xwRmE5JTBBbHBRTDZKTDFhUXdtRFI3NFR4WUdCQUlpNWY0STVUSm9DQ0VxUkh6OTFrcEc2VXZ5bj"
        "J0TG1uSWRKYlBFNHZZdiUwQVdMcnRYWGZGQlNTUEQ0QWZuNyUyQjMvWFVnZ0FsYzdvQ1Rpek9mYmJ0T0ZsWUE0ZzVL"
        "Y1lnUzFKMlpBZU1RcWJVZCUwQVpzZVpDY2FaWlpuNjV0ZHFlZThVWFpsRHZ4MCUyQk5kTzBMUiUyQjVwRnklMkJqdU"
        "0wd1didTU5TXZ6Y21UWGJqc2k3SFklMEE2emQ1M1lxNUsyNDRmd0ZIUlE4ZU9CMElXQiUyQjRQZk03RmVBQXBadmxm"
        "cWxLT2xMY1pMMnV5Vm16Umt5UjV5VzclMEEydW85bWVoWDQ0Q2lQSjJmc2U5WTZlUXRjZkVoTVBrbUhYSTAxc04lMk"
        "JLd1BicEEzOSUyQnhPc1N0amhQOU4xWTFhMiUwQXRRQVZvJTJCeVZnTGdWMkh3czczRmMwbzN3Qzc4cVBFQSUyQnYy"
        "YVJzL0JlM1pGRGdEeWdoYy8xZmdVJTJCN0MlMkJQNmticSUwQWQ0cG95YjZJVzhLQ0pieGZNSnZrb3JkTk9nT1VVeG"
        "5kUEhFaS90Yi9VN3VMakxPZ1BBJTNEJTNEJTBBLS0tLS1FTkQlMjBDRVJUSUZJQ0FURS0tLS0tJTBBLS0tLS1CRUdJ"
        "TiUyMENFUlRJRklDQVRFLS0tLS0lMEFNSUlGU3pDQ0E3T2dBd0lCQWdJSkFORUhkbDB5bzdDVU1BMEdDU3FHU0liM0"
        "RRRUJDd1VBTUg0eEN6QUpCZ05WJTBBQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpEUVRFVU1CSUdBMVVFQnd3TFUyRnVk"
        "R0VnUTJ4aGNtRXhHakFZQmdOViUwQUJBb01FVWx1ZEdWc0lFTnZjbkJ2Y21GMGFXOXVNVEF3TGdZRFZRUUREQ2RKYm"
        "5SbGJDQlRSMWdnUVhSMFpYTjAlMEFZWFJwYjI0Z1VtVndiM0owSUZOcFoyNXBibWNnUTBFd0lCY05NVFl4TVRFME1U"
        "VXpOek14V2hnUE1qQTBPVEV5JTBBTXpFeU16VTVOVGxhTUg0eEN6QUpCZ05WQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQU"
        "pEUVRFVU1CSUdBMVVFQnd3TCUwQVUyRnVkR0VnUTJ4aGNtRXhHakFZQmdOVkJBb01FVWx1ZEdWc0lFTnZjbkJ2Y21G"
        "MGFXOXVNVEF3TGdZRFZRUUQlMEFEQ2RKYm5SbGJDQlRSMWdnUVhSMFpYTjBZWFJwYjI0Z1VtVndiM0owSUZOcFoyNX"
        "BibWNnUTBFd2dnR2lNQTBHJTBBQ1NxR1NJYjNEUUVCQVFVQUE0SUJqd0F3Z2dHS0FvSUJnUUNmUEdSJTJCdFhjOHUx"
        "RXRKekxBMTBGZXUxV2clMkJwN2UlMEFMbVNSbWVhQ0hia1ExVEYzTndsM1JtcHFYa2VHek5MZDY5UVVuV292WXlWU2"
        "5kRU15WWMzc0hlY0dnZmluRWVoJTBBcmdCSlNFZHNTSjlGcGFGZGVzanN4cXpHUmEyMFBZZG5uZldjQ1R2Rm91bHBi"
        "RlI0VkJ1WG5uVkxWemtVdmxYVCUwQUwvVEFuZDhuSVprMHpaa0ZKN1A1THRlUHZ5a2thcjdMY1NRTzg1d3RjUWUwUj"
        "FSYWYvc1E2d1lLYUttRmdDR2UlMEFOcEVKVW1nNGt0YWw0cWdJQXhrJTJCUUhVeFFFNDJzeFZpTjVtcWdsQjBRSmRV"
        "b3QvbzlhL1YvbU1lSDhLdk9BaVElMEFieWlua05uZG4lMkJCZ2s1c1NWNURGZ0YwRGZmVnFtVk1ibHQ1cDNqUHRJbX"
        "pCSUgwUVFyWEpxMzlBVDhjUndQNUglMEFhZnVWZUxIY0RzUnA2aG9sNFAlMkJaRklodThtbWJJMXUwaEgzVy8wQzJC"
        "dVlYQjVQQyUyQjVpekZGaC9uUDBsYzJMZiUwQTZyRUxPOUxaZG5PaHBMMUV4Rk9xOUgvQjh0UFE4NFQzU2diNG5BaW"
        "ZEYWJOdC96dTZNbUNHbzVVOGx3RUZ0R00lMEFSb09hWDRBUyUyQjkwOXgwMGxZbm10d3NEVld2OXZCaUpDWFJzQ0F3"
        "RUFBYU9CeVRDQnhqQmdCZ05WSFI4RVdUQlglMEFNRldnVTZCUmhrOW9kSFJ3T2k4dmRISjFjM1JsWkhObGNuWnBZMl"
        "Z6TG1sdWRHVnNMbU52YlM5amIyNTBaVzUwJTBBTDBOU1RDOVRSMWd2UVhSMFpYTjBZWFJwYjI1U1pYQnZjblJUYVdk"
        "dWFXNW5RMEV1WTNKc01CMEdBMVVkRGdRVyUwQUJCUjRRM3QycG42ODBLOSUyQlFqZnJOWHc3aHdGUlBEQWZCZ05WSF"
        "NNRUdEQVdnQlI0UTN0MnBuNjgwSzklMkJRamZyJTBBTlh3N2h3RlJQREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lE"
        "VlIwVEFRSC9CQWd3QmdFQi93SUJBREFOQmdrcSUwQWhraUc5dzBCQVFzRkFBT0NBWUVBZUY4dFlNWElDdlFxZVhZUU"
        "lUa1Yyb0xKc3A2SjRKQXFKYWJIV3hZSkhHaXIlMEFJRXF1Y1JpSlNTeCUyQkhqSUpFVVZhajhFMFFqRXVkNlk1bE5t"
        "WGxjanFSWGFDUE9xSzBlR1J6NmhpJTJCcmlwTXRQWiUwQXNGTmFCd0xRVlY5MDVTRGpBekR6TklEbnJjblh5QjRnY0"
        "RGQ3Z3REZLS2dMUmpPQi9XQXFnc2NEVW9HcTVaVmklMEF6TFV6VHFpUVBtVUxBUWFCOWM2T3RpNnNuRUZKaUNRNjdK"
        "THlXL0U4My9mcnpDbU81UnU2V2pVNHRtc215OFJhJTBBVWQ0QVBLMHdaVEd0ZlBYVTd3JTJCSUJkRzVFejBrRTFxen"
        "hHUWFMNGdJTkoxek15bGVEbmJ1UzhVaWNqSmlqdnFBJTBBMTUyU3EwNDlFU0R6JTJCMXJSR2MyTlZFcWgxS2FHWG10"
        "WHZxeFhjVEIlMkJMank1Qncya2UwdjhpR25nRkJQcUNUVkIlMEEzb3A1S0JHM1JqYkY2UlJTend6dVdmTDdRRXJOQz"
        "hXRXk1eURWQVJ6VEE1JTJCeG1CYzM4OHY5RG0yMUhHZmNDOE8lMEFERCUyQmdUOXNTcHNzcTBhc2Ntdkg0OU1PZ2p0"
        "MXlveXNMdGRDdEpXLzlGWnBvT3lwYUh4MFIlMkJtSlRMd1BYVk1ydiUwQURhVnpXaDVhaUV4JTJCaWRrU0dNblglME"
        "EtLS0tLUVORCUyMENFUlRJRklDQVRFLS0tLS0lMEFcciIsImlhc1JlcG9ydCI6IntcImlkXCI6XCIxMDQwNTM0MTA0"
        "NzgwNDg4ODI2MzM3NDY4NDQ2NjU0MzIxOTc0NzhcIixcInRpbWVzdGFtcFwiOlwiMjAyMC0wOS0xMVQxOTozMzo1My"
        "4wNTE0NjhcIixcInZlcnNpb25cIjo0LFwiZXBpZFBzZXVkb255bVwiOlwib3lCOVRXeGtFQzltUmxkbFUrMXgvL1cx"
        "L3RUalRhTk9tNFRYYnliNVk2cFJ5ZC9SMU83YmhGZ3Rpc2ZkNmFxUGVBaG5Ra2loaStPS2RVMWI1MmZhRURxZ2ZXZy"
        "9kOW9MczNaSHZFdTR6NldqVENLMHFlY0JPK2JuNlJ5YWc2UHhFT09XOStJRUE4b1VpNzRzZi9jNWtCOHUxTlVTdHA2"
        "VEpjcnBUOTNZdXZJPVwiLFwiYWR2aXNvcnlVUkxcIjpcImh0dHBzOi8vc2VjdXJpdHktY2VudGVyLmludGVsLmNvbV"
        "wiLFwiYWR2aXNvcnlJRHNcIjpbXCJJTlRFTC1TQS0wMDMyMFwiLFwiSU5URUwtU0EtMDAzMjlcIixcIklOVEVMLVNB"
        "LTAwMjIwXCIsXCJJTlRFTC1TQS0wMDI3MFwiLFwiSU5URUwtU0EtMDAyOTNcIl0sXCJpc3ZFbmNsYXZlUXVvdGVTdG"
        "F0dXNcIjpcIkdST1VQX09VVF9PRl9EQVRFXCIsXCJwbGF0Zm9ybUluZm9CbG9iXCI6XCIxNTAyMDA2NTA0MDAwMTAw"
        "MDAwRjBGMDIwNDAxODAwNzAwMDAwMDAwMDAwMDAwMDAwMDBCMDAwMDBCMDAwMDAwMDIwMDAwMDAwMDAwMDAwQjU0Nj"
        "E4NzMxMkZDNzQ2MUE5RTdDNENBQ0MwRUI0NUVEM0U1NzY3M0EyNUU1NkJGNUYzQjMxRDI4RjA2REIyOEE2MjA5NzQx"
        "N0JENjUxRUU2OTUxM0Y5QTU5MTE3RDJGNkQxQ0VEODMzNzc5MTUwNjI4NDFBODQxRTJCMjk2MjU5OTRcIixcImlzdk"
        "VuY2xhdmVRdW90ZUJvZHlcIjpcIkFnQUJBRlFMQUFBTEFBb0FBQUFBQVBUVktTZ2N6dE9yWUpLa05RaXJrM1lBQUFB"
        "QUFBQUFBQUFBQUFBQUFBQUFCZzcvQlFHQUFRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU"
        "FBQUFBQUFBQUFBQUFBQndBQUFBQUFBQUFIQUFBQUFBQUFBRDRQUC90RUM1NHhmRTl6RXFEV1JQL0FVdmRrVTFCV1RV"
        "TlliWUVDWmpOWUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFNUWlRZ0wyZUw0a3RHNG"
        "9SL3g1emdsNkxaN01nclVBc1JxZjg5bHU2U1ZBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB"
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU"
        "FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB"
        "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFESGRlZTNWKzNtTU0wS29SRTcwUUptR3JPSUtjcF"
        "Nwa0lxdDRLR0x5YUdSZ0FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQVwifSJ9Cg==");

    std::string evidence = base64_decode(b64evidence);

    std::string expected_statement("1234567890");
    std::string wrong_expected_statement("wrong");
    std::string expected_code_id(
        "3E0F3FFB440B9E317C4F7312A0D644FFC052F7645350564D43586D8102663358");
    std::string wrong_expected_code_id(
        "2E0F3FFB440B9E317C4F7312A0D644FFC052F7645350564D43586D8102663358");

    LOG_INFO("evidence: %s\n", evidence.c_str());

    bool b;

    // test normal situation
    b = verify_evidence((uint8_t*)b64evidence.c_str(), b64evidence.length(),
        (uint8_t*)expected_statement.c_str(), expected_statement.length(),
        (uint8_t*)expected_code_id.c_str(), expected_code_id.length());
    COND2ERR(!b);

    // test with wrong statement
    b = verify_evidence((uint8_t*)b64evidence.c_str(), b64evidence.length(),
        (uint8_t*)wrong_expected_statement.c_str(), wrong_expected_statement.length(),
        (uint8_t*)expected_code_id.c_str(), expected_code_id.length());
    COND2ERR(b);

    // test with wrong code id
    b = verify_evidence((uint8_t*)b64evidence.c_str(), b64evidence.length(),
        (uint8_t*)expected_statement.c_str(), expected_statement.length(),
        (uint8_t*)wrong_expected_code_id.c_str(), wrong_expected_code_id.length());
    COND2ERR(b);

    return true;

err:
    return false;
}
